# Assignment 2019 Programming for Data Analysis
## Due: last commit on or before November 11th

1. Explain the overall purpose of the numpy.random package in Python.
2. Explain the use of the “Simple random data” and “Permutations” functions.
3. Explain the use and purpose of at least five “Distributions” functions.
4. Explain the use of seeds in generating pseudorandom numbers.
***

## Section 1: Explain the overall purpose of the numpy.random package in Python.

NumPy, short for Numerical Python, is a linear algebra library in Python that most data science Python packages e.g, Mat−plotlib and Scikit-learn are built on.  NumPy works with collections of Python objects called multi-dimensional arrays this data structure is called ndarray (n-dimensional array).


The Python numpy.random package generates random sample numbers, this function is useful when there is a requirement for
unpredictability.  
The Python Library warns that the package should not be used for cryptographic purposes. 


Almost all module functions depend on the basic function random(), which generates a random float uniformly in the half-open range [low, high) [0.0  , 1)
The square brackets indicate where the numbers start and the round brackets show that the highest range is 1 but does not include 1.

The basic random ( ) function will return a uniform distribution of numbers.
If a different type of distribution is required - there are many more to choose from. 
The Mersenne Twister pseudorandom number generator (PRNG) algorithm is used to generate numbers.
***


In [51]:
# example 1 of 3 with comments
#Python Tutorial: Generate Random Numbers and Data Using the random Module https://www.youtube.com/watch?v=KzqSDvzOFNA
#The most basic use of the command - produces numbers between 0 and up to but not including 1
#Each time this command is called it will produce a different number
import numpy as np
import random
#when the parenthesis are left empty, the output defaults to one.
random.random()

0.555607972776598

In [63]:
#the inclusion of 7 produces an array of 7 random numbers
np.random.random(7)

array([0.23397467, 0.37524756, 0.7571289 , 0.40336663, 0.29832748,
       0.99551737, 0.8400615 ])

In [53]:
# example 2 of 3 with comments
#the randint() method can be used for example to recreate the result of rolling a dice becuase it will produce integers
#from the numpy random module, import randint - the command that returns random integers from your indicated
#selection of low to high
#call random.randint(1, 6)
random.randint(1, 6)

2

In [60]:
# example 3 of 3 with comments
#something more advanced, also an example of data

## Section 2: Explain the use of the “Simple random data” and “Permutations” functions.

1. _Simple Random Data_
INCLUDE EXAMPLE COdING WITH COMMENTS
1. _Permutations_
There are two functions - shuffle and permutation
Shuffle modifies the contents of a sequence by "shuffling" its contents.
Permute  rearranges the array,in the case of a multi-dimensional array, it is only shuffled along its first index.

***

In [73]:
#to demonstrate an example of shuffle
#first create a range called a
a=np.arange (10)

In [74]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
#pass the argument of a into the shuffle function
#the array is rearranged.
np.random.shuffle (a)

In [77]:
a

array([9, 8, 6, 2, 5, 0, 3, 4, 7, 1])

In [79]:
np.random.permutation(a)

array([9, 1, 7, 3, 0, 2, 5, 8, 6, 4])

## Section 3: Explain the use and purpose of at least five “Distributions” functions.

The "Distributions" functions are the heavy lifters of Numpy.  


In [69]:
#uniform
#produce an array of 7 random floating point numbers between 10 and 20
#the output is in a continuous uniform distribution
np.random.uniform (10,20,7)

array([14.49975421, 14.10940803, 12.60299691, 18.70395688, 11.85039927,
       10.19661425, 19.53252032])

## Section 4: Explain the use of seeds in generating pseudorandom numbers.

The topic of seeds and random number generation is currently an active area of research.  
Computers have difficulty generating truly random numbers and require a mechanism to do so; therefore 
a number is not actually random but appears to be so i.e., pseudorandom.

The term "seed" refers to the starting position of generating pseudo-random numbers which then uses an algorithim to continue producing numbers e.g. multiplying this by a large number then taking modulo (remainder after division) of the product
It relates to the time when the number was generated, that is when the numpy random generator is imported onto your 
machine the seed is selected and holds from that moment on.  

If the seed is known/set it is possible to predict the pattern because the algorithm will do the same equation and return the same numbers at  each iteration. 
Setting the seed is useful when testing code, e.g., a script can calculate results based on a 
random selection of numbers, then after debugging, test the code again using the same selection of numbers so that the code will do the same thing.


When seemingly random numbers are required: do not set the seed. 
To get the most random numbers for each run, call numpy.random.seed(). This will cause numpy to set the seed to a random number obtained from /dev/urandom or its Windows analog or, if neither of those is available, it will use the clock.
***

In [ ]:
#INCLUDE 3 SAMPLE SCRIPTS

In [31]:
#In order to illustrate the use of seed function I will compare two scripts
#from the numpy random module, import randint - the command that returns random integers from your indicated
#selection of low to high
from random import randint
#print a selection of 10 random integers between 1 and 10
for i in range (10):print (randint(1,10))
#this command just prints one integer: print (randint(1,10))

6
9
8
8
5
2
5
7
5
9


In [27]:
#This script first imports seed, then includes the call for the seed function which I have set at 33
#When the seed is set each iteration produces the same sequence.
from random import randint, seed
seed(33)
for i in range (10):print (randint(1,10))

10
3
4
5
8
9
9
3
10
9


In [68]:
#this time using the random function
np.random.seed (33)
np.random.random()

0.24851012743772993