# Assignment 2019 Programming for Data Analysis
## Due: last commit on or before November 11th

1. Explain the overall purpose of the numpy.random package in Python.
2. Explain the use of the “Simple random data” and “Permutations” functions.
3. Explain the use and purpose of at least five “Distributions” functions.
4. Explain the use of seeds in generating pseudorandom numbers.
***

## Section 1: Explain the overall purpose of the numpy.random package in Python.

NumPy, short for Numerical Python, is a linear algebra library in Python that most data science Python packages e.g, Mat−plotlib and Scikit-learn are built on.  NumPy specialises in working with large collections of Python objects called multi-dimensional arrays, this data structure is called ndarray (n-dimensional array).


The Python numpy.random package generates random sample numbers, this function is useful when there is a requirement for
unpredictability.  
The Python Library warns that the package should not be used for cryptographic purposes. 


Almost all module functions depend on the basic function random(), which generates a random float uniformly in the half-open range [low, high) [0.0  , 1)


The square brackets indicate where the numbers start and the round brackets show that the highest range is 1 but does not include 1. 0 <= n <1.0

The basic random ( ) function will return a uniform distribution of numbers.
If a different type of distribution is required - there are many more to choose from. 
The "Mersenne Twister" pseudo random number generator (PRNG) algorithm is used to generate numbers in numpy.
A true random number generator is usually hardware based.


***


## Examples of the numpy random package

In [5]:
#The most basic use of the command - produces numbers between 0 and up to but not including 1
#Each time this command is called it will produce a different number
import numpy as np
import random
#when the parenthesis are left empty, the output defaults to one.
np.random.random()

0.11701960276120171

In [4]:
#the inclusion of 7 produces an array of 7 random numbers
np.random.random(7)

array([0.96023632, 0.50941424, 0.26573327, 0.1861572 , 0.65105583,
       0.38075873, 0.88200824])

In [55]:
#the randint() method (random integer) produces whole numbers
#this is an interesting example that uses the command to recreate the result of rolling a six sided dice
#from the numpy random module, import randint - the command that returns random integers from your indicated
#selection of low to high with the upperbounds being exclusive
#call np.random.randint(1, 7) 7 must beincluded so that 6 can be selected randomly
np.random.randint(1, 7)

6

In [46]:
# example 3 of 3 with comments
#something more advanced, also an example of data

***

## Section 2: Explain the use of the “Simple random data” and “Permutations” functions

### _Simple Random Data_

The simple random data commands offer the most straighforward pseudo random numbers functions for use in scripts. At time of writing there are ten options.
I am going to go into detail of a sample of three (not chosen at random!)

Simple random data function | Description
------------ | -------------
rand(d0, d1, ..., dn)	| Random values in a given shape.<br>
randn(d0, d1, ..., dn)	|  Return a sample (or samples) from the “standard normal” distribution.<br>
randint(low[, high, size, dtype]) |	Return random integers from low (inclusive) to high (exclusive).<br>
random_integers(low[, high, size]) |	Random integers of type np.int between low and high, inclusive.<br>
random_sample([size])	|  Return random floats in the half-open interval [0.0, 1.0).<br>
random([size]) | Return random floats in the half-open interval [0.0, 1.0).<br>
ranf([size]) |	Return random floats in the half-open interval [0.0, 1.0).<br>
sample([size])|	Return random floats in the half-open interval [0.0, 1.0).<br>
choice(a[, size, replace, p])	|Generates a random sample from a given 1-D array<br>
bytes(length)	|  Return random bytes.<br>

In [82]:
#rand(d0, d1, ..., dn)
#calling the rand function produces values in a particular shape of array that is denoted by the appearance of: d0,d1...,dn
#the parameters input influence the "shape"
#but the random numbers created will always be in the half-open range [low, high) [0.0  , 1)
np.random.rand(1,2,3)

array([[[0.29200277, 0.82073726, 0.81774012],
        [0.11436724, 0.7324204 , 0.09730903]]])

In [ ]:
#The supporting documentation advises that this function produces a uniform distribution, i.e. that all numbers have an 
#equal likelihood of being randomly selected
np.random.rand(500,10)
#import matplotlib.pyplot as plt

#plt.hist(a)
#plt.show

In [ ]:
randn(d0, d1, ..., dn)

In [ ]:
randint(low[, high, size, dtype])

In [ ]:
random_integers(low[, high, size])

In [68]:
#nums= [2,4,6,8]
#np.random.sample(nums)

In [63]:
#this example provides an array called nums
#by calling the choice function, a random sample is generated from the given 1-D array
nums= [2,4,6,8]
np.random.choice(nums)

8

In [ ]:
bytes(length)

blank!

### _Summary of Simple Random Data_
These options are useful tools as an introduction to the concept of pseudo random number generation.
When used in conjunction with matplotlib to generate plots of the data, the ideas can be more effectively conveyedfor those without a mathematical background.

### _Permutations_
There are two functions - shuffle and permutation. <br>
Shuffle modifies the contents of a sequence by "shuffling" its contents.<br>
Permute  rearranges the array,in the case of a multi-dimensional array, it is only shuffled along its first index.<br>

In [73]:
#to demonstrate an example of shuffle
#first create a range called a
a=np.arange (10)

In [74]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
#pass the argument of a into the shuffle function
#the array is rearranged.
np.random.shuffle (a)

In [77]:
a

array([9, 8, 6, 2, 5, 0, 3, 4, 7, 1])

In [79]:
np.random.permutation(a)

array([9, 1, 7, 3, 0, 2, 5, 8, 6, 4])

## Section 3: Explain the use and purpose of at least five “Distributions” functions.

The "Distributions" functions are the heavy lifters of Numpy.  


In [69]:
#uniform
#produce an array of 7 random floating point numbers between 10 and 20
#the output is in a continuous uniform distribution
np.random.uniform (10,20,7)

array([14.49975421, 14.10940803, 12.60299691, 18.70395688, 11.85039927,
       10.19661425, 19.53252032])

use this as an example for distributions  https://realpython.com/lessons/randomness-modeling-and-simulation/

## Section 4: Explain the use of seeds in generating pseudorandom numbers.

The topic of seeds and random number generation is currently an active area of research.  
Computers have difficulty generating truly random numbers and require a mechanism to do so; therefore 
a number is not actually random but appears to be so i.e., pseudo random.

The term "seed" refers to the starting position of generating pseudo-random numbers which then uses an algorithim to continue producing numbers e.g. multiplying this by a large number then taking modulo (remainder after division) of the product
It relates to the system time when the number was generated, that is when the numpy random generator is imported onto your 
machine the seed is selected and holds from that moment on.  

If the seed is known/set it is possible to predict the pattern because the algorithm will do the same equation and return the same numbers at  each iteration. 
Setting the seed is useful when demonstrating or testing code, e.g., a script can calculate results based on a 
random selection of numbers, then after debugging, test the code again using the same selection of numbers so that the code will do the same thing.


When seemingly random numbers are required: do not set the seed. 
To get the most random numbers for each run, call numpy.random.seed(). This will cause numpy to set the seed to a random number obtained from /dev/urandom or its Windows analog or, if neither of those is available, it will use the clock.
***

In [ ]:
#INCLUDE 3 SAMPLE SCRIPTS

In [31]:
#In order to illustrate the use of seed function I will compare two scripts
#from the numpy random module, import randint - the command that returns random integers from your indicated
#selection of low to high
from random import randint
#print a selection of 10 random integers between 1 and 10
for i in range (10):print (randint(1,10))
#this command just prints one integer: print (randint(1,10))

6
9
8
8
5
2
5
7
5
9


In [27]:
#This script first imports seed, then includes the call for the seed function which I have set at 33
#When the seed is set each iteration produces the same sequence.
from random import randint, seed
seed(33)
for i in range (10):print (randint(1,10))

10
3
4
5
8
9
9
3
10
9


In [68]:
#this time using the random function
np.random.seed (33)
np.random.random()

0.24851012743772993